### ISSUE TITLE
Unauthorized Error 401. Tried to regenerate tokens but still issue persists

### ISSUE THREAD

**Issue by M-Ather** [twitterdev/Twitter-API-v2-sample-code#69]
I am using python sample code provided in the repository. But I am getting "builtins.Exception: (401, '{\n "title": "Unauthorized",\n "type": "about:blank",\n "status": 401,\n "detail": "Unauthorized"\n}')" error whenever I try to fetch data using any Endpoint. I tried to regenerate tokens with Read, Write Permissions but still the issue persists.

**Comment by andypiper** [comment]
Have you set the correct environment variables?

**Comment by arb-man-zk** [comment]
Yes - to follow up. Same thing happening to me intermittently. Not sure if it is the control c exit not working properly in node.js, but once it quits on a timeout, it gives me a 401 error when i re open.

**Comment by ikemHood** [comment]
I do hava same error. Making a recent searce with axios (Js) and header contains a bearer token which keeps responding Unauthorized. tried using it on Postman too with the same error. I have regenerated to no avail.

**Comment by andypiper** [comment]
- Is the app part of a project with v2 access?
- What level of access do you have to the API (this should work fine with Essential Access but just want to check)

**Comment by AkaiSedo** [comment]
It is part of v2 access and so far I have Essential account.
I managed to get it to work with needle (maybe temporary issue from twitter side?) but still get some error with axios.
Not sure where the problem is but for now I have a working implementation so I will dig further!

**Comment by opostavnicha** [comment]
I keep getting the same error, both using Python and Postman..

**Comment by serdarzuli** [comment]
this case it's still open , omg why ? 
why nobody helps us ?
i have same problem :/

**Comment by vardhans07** [comment]
401
Traceback (most recent call last):
  File "c:\Users\dell\Desktop\try_1\tw_se_3.py", line 41, in <module>
    main()
  File "c:\Users\dell\Desktop\try_1\tw_se_3.py", line 36, in main
    json_response = connect_to_endpoint(search_url, query_params)
  File "c:\Users\dell\Desktop\try_1\tw_se_3.py", line 31, in connect_to_endpoint
    raise Exception(response.status_code, response.text)
Exception: (401, '{\n  "title": "Unauthorized",\n  "type": "about:blank",\n  "status": 401,\n  "detail": "Unauthorized"\n}')

[Done] exited with code=1 in 2.356 seconds

**Comment by 125569489** [comment]
You can try this https://twitter.utools.me/ tel: https://t.me/Yang0619

**Comment by realHakeen** [comment]
me 22222
